site_name: Godot Kotlin/JVM
docs_dir: src/doc

repo_name: 'utopia-rise/godot-kotlin-jvm'
repo_url: 'https://github.com/utopia-rise/godot-kotlin-jvm'

theme:
  name: material
  favicon: assets/img/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Light mode
  logo: assets/img/logo.png
  font:
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/utopia-rise

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - meta

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js
  - js/init.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css

nav:
  - Home: index.md
  - Getting started:
      - Requirements: getting-started/requirements.md
      - Setting up: getting-started/setting-up.md
      - Your first Class: getting-started/your-first-class.md
  - User guide:
    - API differences: user-guide/api-differences.md
    - Classes: user-guide/classes.md
    - Compiling your project: user-guide/compiling-your-project.md
    - Properties: user-guide/properties.md
    - Signals: user-guide/signals.md
    - Functions: user-guide/functions.md
    - Exporting: user-guide/exporting.md
    - Debugging: user-guide/debugging.md
    - Consuming libraries: user-guide/consuming-libraries.md
    - Versioning: user-guide/versioning.md
    - Supported platforms: user-guide/supported-platforms.md
    - Advanced:
      - Abstract Classes: user-guide/advanced/abstract-classes.md
      - Custom Source Directories: user-guide/advanced/custom-src-dirs.md
      - Custom Gradle Wrapper path: user-guide/advanced/custom-gradle-wrapper-path.md
      - Gradle Plugin configuration: user-guide/advanced/gradle-plugin-configuration.md
      - Command-line Arguments: user-guide/advanced/commandline-args.md
      - Kotlin Singletons: user-guide/advanced/kotlin-singleton.md
      - GraalVM native-image: user-guide/advanced/graal-vm-native-image.md
  - Develop libraries:
      - Introduction: develop-libraries/introduction.md
      - Setup: develop-libraries/setup.md
      - Publishing: develop-libraries/publishing.md
  - Contributing:
    - General: contribution/general.md
    - Guidelines: contribution/guidelines.md
    - Setup: contribution/setup.md
    - Build with C# support: contribution/build-with-csharp-support.md
    - Support for other JVM-based languages: contribution/support-for-other-jvm-based-languages.md
    - Knowledge Base:
        - Artefact Differentiation: contribution/knowledge-base/artefact-differentiation.md
        - Entry Generation: contribution/knowledge-base/entry-generation.md
        - Shared Buffer: contribution/knowledge-base/shared-buffer.md
        - Memory Management: contribution/knowledge-base/memory-management.md